import type { NextPage } from "next";
import Head from "next/head";
import { Playground } from "../components/playground";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Gemock (Generate everything mock)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://gemock.com">Gemock</a>
        </h1>

        <p className={styles.description}>
          Generate mock data using{" "}
          <code className={styles.code}>http:/gemock.com/api</code>
        </p>
        <Playground />
      </main>
    </div>
  );
};

export default Home;
